GET http://localhost:5107/

###
GET http://localhost:5107/students

###
GET http://localhost:5107/students/3

###
POST http://localhost:5107/students
Content-Type: application/json

{
    "name": "Amr",
    "gender": "Male",
    "birthData": "2000-1-2"
}

###
PUT http://localhost:5107/students/3
Content-Type: application/json

{
    "name": "Ahmed Sayed Zizo",
    "gender": "Male",
    "birthData": "1996-1-10"
}

